name: atlas-engine-test-one

type: rails

up:
  - homebrew:
      - mysql-client@5.7:
          or: [mysql@5.7]
          conflicts: [mysql-connector-c, mysql, mysql-client]
    # - another_package
  - ruby: 3.2.1
  - bundler
  - isogun
  - database:
      bootstrap: bin/rails db:setup db:migrate
      migrate: bin/rails db:migrate db:test:prepare
      host: atlas-engine-test-one.railgun
      user: root
      password: ''
      database: atlas_engine_test_one_development

server:
  port: 24607

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run: cd $USER_PWD && bin/rails test $@
  typecheck:
    desc: 'run Sorbet typechecking'
    aliases: ['tc']
    depends-isogun: false
    run: bin/srb tc
    subcommands:
      ruby:
        desc: 'run Sorbet typechecking'
        run: bin/srb tc
  update-rbis:
    desc: 'updates the RBI files corresponding to gems listed in the Gemfile'
    depends-isogun: false
    run: bin/tapioca gem
  style:
    desc: 'Run rubocop'
    run: cd $USER_PWD && bundle exec rubocop
    subcommands:
      ruby:
        syntax:
          optional: --include-branch-commits --all-cops
        desc: 'Run Rubocop checks. Add --include-branch-commits to run on all files changed on the current branch. Add --all-cops to run all the cops.'
        run: cd $USER_PWD && bundle exec rubocop

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  'My Application': https://atlas-engine-test-one.myshopify.io
  #ops:
  # - https://datadog.link
  # - https://bugsnag.link
  # - https://kafka.link
