version: "3.8"

services:
  database:
    image: mysql:8.2.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    mem_limit: 2G
    ports:
      - 3306:3306
    volumes:
      - "mysql-data:/var/lib/mysql"

  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elasticsearch/Dockerfile
    container_name: elasticsearch
    mem_limit: 4G
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  mysql-data:
    driver: local
  elasticsearch-data:
    driver: local
