name: CI

on: [push]

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }} / ${{ matrix.database }}
    runs-on: shopify-ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile: [Gemfile, gemfiles/rails_6_0.gemfile, gemfiles/rails_6_1.gemfile, gemfiles/rails_7_0.gemfile, gemfiles/rails_edge.gemfile]
        ruby: ["3.0", "3.1", "3.2"]
        database: [sqlite]
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DB: ${{ matrix.database }}
      MYSQL_USER: root
      MYSQL_PASSWORD: changeme
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Create .env files
      run: cp .env.template .env && cp .env.template test/dummy/.env

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        cache-version: 1
        rubygems: ${{ matrix.ruby == '3.0' && 'latest' || 'default' }}

    - name: Rails version
      if: ${{ matrix.gemfile == 'gemfiles/rails_edge.gemfile' }}
      run: bundle info rails | head -1

    - name: Set up database
      run: RAILS_ENV=test bundle exec rails db:setup

    - name: Ruby Tests
      run: bundle exec rails test

    - name: Archive system test artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: screenshots
        path: test/dummy/tmp/screenshots
